[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_MAPTILER_KEY = "your-maptiler-key-here"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
